import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Header from "../components/Header/Header";
import Container from "@components/Container";
import styles from "../styles/Home.module.scss";
import Button from "@components/Button";
import products from "../data/products.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.css"
        />
      </Head>
      <Header />
      <main>
        <Container>
          <h1>Related Products</h1>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                // eslint-disable-next-line react/jsx-key
                <li key={product.id}>
                  <Image
                    src={product.Image}
                    alt={`Card of ${product.title}`}
                    width={400}
                    height={270}
                  />
                  <h3>{product.title}</h3>
                  <p>${product.Price}</p>
                  <p>
                    <Button>Add to Cart</Button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <Script
        async
        src="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.js"
      />
      <div
        hidden
        id="snipcart"
        data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
      />
    </div>
  );
}
